package main

func handleerror(err error) {
	if err != nil {
		panic(err)
	}

}
